[book]
title = "lemonfiber specification"
description = "The canonical specification for the lemonfiber project."
authors = ["NightWorks.io"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/lemonfiber/spec"
edit-url-template = "https://github.com/lemonfiber/spec/edit/main/{path}"
