#!/usr/bin/env python3
"""Generate the feature board from truth: feature frontmatter joined with the
version manifests.

Writes ``10-functional/features/index.json`` (the whole board in one file, for
tools) and ``10-functional/features/BOARD.md`` (the human view). Regenerated by
``just board``; a CI check fails if the committed copies drift. Run from the repo
root.
"""
import json
import glob
import re
import tomllib
import pathlib

import metafm

FEATDIR = "10-functional/features"

REQ_DEF = re.compile(r"^\|\s*\*\*([A-Z]+\d*-R\d+)\*\*\s*\|", re.M)


def count_requirements(feats):
    """Requirement rows across the feature files, so the scale is stated once."""
    total = 0
    for fm in feats.values():
        text = pathlib.Path(fm["path"]).read_text(encoding="utf-8")
        total += len(REQ_DEF.findall(text))
    return total


def area_span(rows):
    """The first and last area letter in use, as they are written in prose."""
    areas = sorted({row["area"] for row in rows})
    return f"{areas[0]}\u2013{areas[-1]}"


def _order(fid):
    return (fid[0], int(fid[1:]))


def load_features():
    feats = {}
    for path in sorted(glob.glob(f"{FEATDIR}/[a-l]-*/*.md")):
        fm = metafm.load(path)
        if fm and "id" in fm:
            fm["path"] = path
            feats[fm["id"]] = fm
    return feats


VERSION_MANIFESTS = "70-operations/versions/*.toml"


def version_manifests():
    """Every version manifest, TEMPLATE excluded, as parsed data."""
    for vf in sorted(glob.glob(VERSION_MANIFESTS)):
        if pathlib.Path(vf).stem != "TEMPLATE":
            yield tomllib.loads(pathlib.Path(vf).read_text(encoding="utf-8"))


def load_versions():
    """feature id -> {version: status}, from each manifest's goals."""
    by_feature = {}
    for data in version_manifests():
        version, status = data["version"], data.get("status", "planned")
        for goal in data.get("goals", []):
            feature = goal.split("-R")[0]
            by_feature.setdefault(feature, {})[version] = status
    return by_feature


def load_version_list():
    """Every version manifest as a train row, ordered by semver. Unlike the
    per-feature version membership above, this keeps the epoch-closing majors —
    which own no per-feature goals (the no-stub-major rule) and so appear in no
    feature row — so a consumer can render the whole train, majors included."""
    versions = []
    for data in version_manifests():
        versions.append({
            "version": data["version"],
            "epoch": data.get("epoch"),
            "status": data.get("status", "planned"),
            "milestone": data.get("milestone"),
            "closes_epoch": data.get("closes_epoch"),
            "goals": len(data.get("goals", [])),
        })
    versions.sort(key=lambda v: [int(part) for part in v["version"].split(".")])
    return versions


def milestones_by_version():
    """Which milestone each version serves, declared once on the manifest.

    The feature files used to carry a `milestone:` of their own, and it disagreed
    with the roadmap — the television interface was tagged to one milestone while
    the roadmap called it another, and thirty features carried none at all. A
    feature belongs to whatever milestone the version shipping it serves, so that
    is where it is read from and there is nothing left to drift.
    """
    return {data["version"]: data.get("milestone") for data in version_manifests()}


def milestones_of(feature_id, by_feature, by_version):
    """Every milestone this feature contributes to, in version order.

    A feature is not always one milestone's work. Lifecycle control ships its
    first requirements with the core CLI and its interactive surface with the
    television interface, and attributing all of it to whichever came first made
    the later milestone look empty — which is exactly how a milestone with real
    work in it came to read as having one item.
    """
    seen = []
    for version in sorted(
        by_feature.get(feature_id, {}),
        key=lambda v: [int(part) for part in v.split(".")],
    ):
        milestone = by_version.get(version)
        if milestone and milestone not in seen:
            seen.append(milestone)
    return seen


def build_rows(feats, by_feature):
    by_version = milestones_by_version()
    rows = []
    for fid in sorted(feats, key=_order):
        fm = feats[fid]
        versions = [
            {"version": v, "status": s}
            for v, s in sorted(by_feature.get(fid, {}).items())
        ]
        rows.append({
            "id": fid,
            "title": fm["title"],
            "area": fm["area"],
            "audience": fm["audience"],
            "kind": fm.get("kind", "feature"),
            "status": fm["status"],
            "tracks": fm["tracks"],
            "milestones": milestones_of(fid, by_feature, by_version),
            "milestone": next(iter(milestones_of(fid, by_feature, by_version)), None),
            "priority": fm.get("priority"),
            "labels": fm.get("labels", []),
            "requires": fm.get("requires", []),
            "relates": fm.get("relates", []),
            "versions": versions,
            "path": fm["path"].split("features/", 1)[1],
        })
    return rows


def render_board(rows, counts):
    def ships(row):
        return ", ".join(f"`{v['version']}`" for v in row["versions"]) or "—"

    out = [
        "# Feature board",
        "",
        "**Status:** Accepted",
        "",
        "Generated from feature frontmatter and the version manifests by",
        "`scripts/gen_board.py` — do not edit by hand; `just board` regenerates it.",
        "",
        f"**{counts['features']} features** in areas {counts['areas']}, "
        f"**{counts['requirements']} requirements**.",
        "Counted here rather than restated: prose that quotes a number goes stale",
        "silently, and this file is regenerated from the features themselves.",
        "",
    ]
    for track, label in (
        ("v1", "v1 — the product (areas A–G, and L1 to release it)"),
        ("v2", "v2 — the ecosystem (areas H–K, plus F3, and L2 to release it)"),
    ):
        out += [
            f"## {label}",
            "",
            "| ID | Feature | Area | Audience | Status | Ships in |",
            "|----|---------|------|----------|--------|----------|",
        ]
        for row in rows:
            if row["tracks"] != track:
                continue
            out.append(
                f"| [{row['id']}]({row['path']}) | {row['title']} | {row['area']} "
                f"| {row['audience']} | {row['status']} | {ships(row)} |"
            )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    feats = load_features()
    rows = build_rows(feats, load_versions())
    counts = {
        "features": len(rows),
        "requirements": count_requirements(feats),
        "areas": area_span(rows),
    }
    index = {
        "generated_by": "scripts/gen_board.py",
        "counts": counts,
        "versions": load_version_list(),
        "features": rows,
    }
    pathlib.Path(f"{FEATDIR}/index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    pathlib.Path(f"{FEATDIR}/BOARD.md").write_text(render_board(rows, counts), encoding="utf-8")
    print(f"board: {counts['features']} features, {counts['requirements']} requirements -> index.json + BOARD.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
