#!/usr/bin/env python3
"""Generate the feature board from truth: feature frontmatter joined with the
version manifests.

Writes ``10-functional/features/index.json`` (the whole board in one file, for
tools) and ``10-functional/features/BOARD.md`` (the human view). Regenerated by
``just board``; a CI check fails if the committed copies drift. Run from the repo
root.
"""
import json
import glob
import tomllib
import pathlib

import metafm

FEATDIR = "10-functional/features"


def _order(fid):
    return (fid[0], int(fid[1:]))


def load_features():
    feats = {}
    for path in sorted(glob.glob(f"{FEATDIR}/[a-k]-*/*.md")):
        fm = metafm.load(path)
        if fm and "id" in fm:
            fm["path"] = path
            feats[fm["id"]] = fm
    return feats


def load_versions():
    """feature id -> {version: status}, from each manifest's goals."""
    by_feature = {}
    for vf in sorted(glob.glob("70-operations/versions/*.toml")):
        if pathlib.Path(vf).stem == "TEMPLATE":
            continue
        data = tomllib.loads(pathlib.Path(vf).read_text(encoding="utf-8"))
        version, status = data["version"], data.get("status", "planned")
        for goal in data.get("goals", []):
            feature = goal.split("-R")[0]
            by_feature.setdefault(feature, {})[version] = status
    return by_feature


def load_version_list():
    """Every version manifest as a train row, ordered by semver. Unlike the
    per-feature version membership above, this keeps the epoch-closing majors —
    which own no per-feature goals (the no-stub-major rule) and so appear in no
    feature row — so a consumer can render the whole train, majors included."""
    versions = []
    for vf in sorted(glob.glob("70-operations/versions/*.toml")):
        if pathlib.Path(vf).stem == "TEMPLATE":
            continue
        data = tomllib.loads(pathlib.Path(vf).read_text(encoding="utf-8"))
        versions.append({
            "version": data["version"],
            "epoch": data.get("epoch"),
            "status": data.get("status", "planned"),
            "closes_epoch": data.get("closes_epoch"),
            "goals": len(data.get("goals", [])),
        })
    versions.sort(key=lambda v: [int(part) for part in v["version"].split(".")])
    return versions


def build_rows(feats, by_feature):
    rows = []
    for fid in sorted(feats, key=_order):
        fm = feats[fid]
        versions = [
            {"version": v, "status": s}
            for v, s in sorted(by_feature.get(fid, {}).items())
        ]
        rows.append({
            "id": fid,
            "title": fm["title"],
            "area": fm["area"],
            "audience": fm["audience"],
            "kind": fm.get("kind", "feature"),
            "status": fm["status"],
            "tracks": fm["tracks"],
            "milestone": fm.get("milestone"),
            "priority": fm.get("priority"),
            "labels": fm.get("labels", []),
            "depends": fm.get("depends", []),
            "versions": versions,
            "path": fm["path"].split("features/", 1)[1],
        })
    return rows


def render_board(rows):
    def ships(row):
        return ", ".join(f"`{v['version']}`" for v in row["versions"]) or "—"

    out = [
        "# Feature board",
        "",
        "**Status:** Accepted",
        "",
        "Generated from feature frontmatter and the version manifests by",
        "`scripts/gen_board.py` — do not edit by hand; `just board` regenerates it.",
        "",
    ]
    for track, label in (
        ("v1", "v1 — the product (areas A–G)"),
        ("v2", "v2 — the ecosystem (areas H–K, plus F3)"),
    ):
        out += [
            f"## {label}",
            "",
            "| ID | Feature | Area | Audience | Status | Ships in |",
            "|----|---------|------|----------|--------|----------|",
        ]
        for row in rows:
            if row["tracks"] != track:
                continue
            out.append(
                f"| [{row['id']}]({row['path']}) | {row['title']} | {row['area']} "
                f"| {row['audience']} | {row['status']} | {ships(row)} |"
            )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    feats = load_features()
    rows = build_rows(feats, load_versions())
    index = {
        "generated_by": "scripts/gen_board.py",
        "versions": load_version_list(),
        "features": rows,
    }
    pathlib.Path(f"{FEATDIR}/index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    pathlib.Path(f"{FEATDIR}/BOARD.md").write_text(render_board(rows), encoding="utf-8")
    print(f"board: {len(rows)} features -> index.json + BOARD.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
